# Generated by Django 4.1.2 on 2022-10-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='to_time',
        ),
    ]
