# Generated by Django 4.1.2 on 2022-10-23 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll', '0003_remove_enroll_to_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('doctor', 'from_time', 'date')},
        ),
    ]
