# Generated by Django 4.1.2 on 2022-10-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
            ],
        ),
    ]
