# Generated by Django 4.1.2 on 2022-10-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcarts',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalcarts',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalcarts',
            name='service',
            field=models.ManyToManyField(to='dental.dentalserviceslist'),
        ),
    ]
