# Generated by Django 4.1.2 on 2022-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0003_rename_medicalcarts_medicalcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcards',
            name='mrt',
            field=models.ImageField(blank=True, null=True, upload_to='mrt_images/'),
        ),
        migrations.AddField(
            model_name='medicalcards',
            name='сonclusion',
            field=models.TextField(null=True),
        ),
    ]
